# Site
repository: Ausername-Asterisk/Ausername-Asterisk.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ken
title: 
email: 
website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
        
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
      title: Harvard University
      caption: 2010 - 2013
      sub_title: BSc Computer Science
      quote: >
      description: |
        # This will include new lines to allow paragraphs
        I started this project as a way of learning <mark>React</mark> and it has since grown into a fully fledged app. 
        I have learned many skills through this and I’m very proud of having this in my portfolio. 
        If you don't have a project as awesome as this, I would advise you to make one.
      
        | Feature                                     | Description                                                                                               | Implementation                                              |
        |---------------------------------------------|-----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------|
        | **Convex & Nonconvex Optimization**         | Implementation of convex optimization using Newton's method and nonconvex optimization with Scipy's minimize function. | [Python (numpy, scipy)](https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/1_Convex_%26_Nonconvex_Optimization_Github.ipynb) |
        | **Linear Programming**                      | Solution of common manufacturing production and electric power network problems using linear programming optimization techniques. | [Python (numpy, cvxpy)](https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/2_Linear_Programming_Github.ipynb) |
        | **Solving Linear Program Using Basic Feasible Solutions** | Identification of all possible basic solutions and determination of the optimal solution among them. | [Python (numpy)](https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/3_Solving_Linear_Program_Using_Basic_Feasible_Solutions_Github.ipynb) |
        | **Solving Linear Program Using Simplex Method** ★ | Implementation of the simplex method from scratch to solve linear programming problems. | [Python (numpy)](https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/4_Solving_Linear_Program_Using_Simplex_Method_Github.ipynb) |
        | **Cutting Stock Problem With Column Generation** ★ | Solution of the cutting stock problem using column generation, applied to solve the pricing problem. | [Python (numpy, cvxpy)](https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/5_Cutting_Stock_Problem_with_Column_Generation_Github.ipynb) |
        | **Location Optimization Using SOCP**         | Application of second-order cone programming to identify optimal locations for optimization problems. | [Python (numpy, cvxpy)](https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/6_Location_Optimization_Using_SOCP_Github.ipynb) |


        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |
          # This will include new lines to allow paragraphs
          I started this project as a way of learning <mark>React</mark> and it has since grown into a fully fledged app. 
          I have learned many skills through this and I’m very proud of having this in my portfolio. 
          If you don't have a project as awesome as this, I would advise you to make one.
        
          <div style="font-size: 18px;">
            <table style="width:100%; border-collapse: collapse;">
              <tr>
                <th style="border: 1px solid black; padding: 8px;">Feature</th>
                <th style="border: 1px solid black; padding: 8px;">Description</th>
                <th style="border: 1px solid black; padding: 8px;">Implementation</th>
              </tr>
              <tr>
                <td style="border: 1px solid black; padding: 8px;"><strong>Convex & Nonconvex Optimization</strong></td>
                <td style="border: 1px solid black; padding: 8px;">Implementation of convex optimization using Newton's method and nonconvex optimization with Scipy's minimize function.</td>
                <td style="border: 1px solid black; padding: 8px;"><a href="https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/1_Convex_%26_Nonconvex_Optimization_Github.ipynb">Python (numpy, scipy)</a></td>
              </tr>
              <tr>
                <td style="border: 1px solid black; padding: 8px;"><strong>Linear Programming</strong></td>
                <td style="border: 1px solid black; padding: 8px;">Solution of common manufacturing production and electric power network problems using linear programming optimization techniques.</td>
                <td style="border: 1px solid black; padding: 8px;"><a href="https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/2_Linear_Programming_Github.ipynb">Python (numpy, cvxpy)</a></td>
              </tr>
              <tr>
                <td style="border: 1px solid black; padding: 8px;"><strong>Solving Linear Program Using Basic Feasible Solutions</strong></td>
                <td style="border: 1px solid black; padding: 8px;">Identification of all possible basic solutions and determination of the optimal solution among them.</td>
                <td style="border: 1px solid black; padding: 8px;"><a href="https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/3_Solving_Linear_Program_Using_Basic_Feasible_Solutions_Github.ipynb">Python (numpy)</a></td>
              </tr>
              <tr>
                <td style="border: 1px solid black; padding: 8px;"><strong>Solving Linear Program Using Simplex Method</strong> ★</td>
                <td style="border: 1px solid black; padding: 8px;">Implementation of the simplex method from scratch to solve linear programming problems.</td>
                <td style="border: 1px solid black; padding: 8px;"><a href="https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/4_Solving_Linear_Program_Using_Simplex_Method_Github.ipynb">Python (numpy)</a></td>
              </tr>
              <tr>
                <td style="border: 1px solid black; padding: 8px;"><strong>Cutting Stock Problem With Column Generation</strong> ★</td>
                <td style="border: 1px solid black; padding: 8px;">Solution of the cutting stock problem using column generation, applied to solve the pricing problem.</td>
                <td style="border: 1px solid black; padding: 8px;"><a href="https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/5_Cutting_Stock_Problem_with_Column_Generation_Github.ipynb">Python (numpy, cvxpy)</a></td>
              </tr>
              <tr>
                <td style="border: 1px solid black; padding: 8px;"><strong>Location Optimization Using SOCP</strong></td>
                <td style="border: 1px solid black; padding: 8px;">Application of second-order cone programming to identify optimal locations for optimization problems.</td>
                <td style="border: 1px solid black; padding: 8px;"><a href="https://github.com/Ausername-Asterisk/KKH-DataTouchesEverything/blob/main/1.%20Optimization/6_Location_Optimization_Using_SOCP_Github.ipynb">Python (numpy, cvxpy)</a></td>
              </tr>
            </table>
          </div>



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
