title: Data Touches Everything 1
theme: jekyll-theme-cayman
show_downloads: false
description: A comprehensive repository uniting theory and practice in Data Science.
logo_url:assets/images/logo.png
colors:
    gradient_left: "#0F4C81"
    gradient_right: "#BB2649"
    header: "#fff"
    # android_theme: "#000" # this default to gradient_color
    # link: "#1e6bb8" # this default to gradient_color
    # section_title: "#155799" # this default to gradient_color
buttons:
    # zip_url: 
    # zip_title: 
      zip_hide: true
    # tar_url: 
    # tar_title: 
      tar_hide: true
      github_hide: true
