title: Data Touches Everything
theme: jekyll-theme-cayman
show_downloads: false
description: A comprehensive repository uniting theory and practice in AI and Data Science.
author:
  name: Ken K. Hong
