title: Data Touches Everything 12
author:
  name: Ken K. Hong
  email: -
description: A comprehensive repository uniting theory and practice in AI and Data Science.

header_pages:
#  - about.md

minima:
  skin: classic  


theme: minima
